[profile.default]
libs = ["lib"]
# optimizer = true
# optimizer_runs = 10000000
out = "out"
src = "src"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
